OS=$(uname)
if [ "$OS" = "Darwin" ]; then
    EXECUTABLE="./cmake-build-release/shader_compiler/ShaderCompiler"
    BACKEND="metal"
else
    EXECUTABLE="./cmake-build-release-visual-studio/shader_compiler/ShaderCompiler.exe"
    BACKEND="opengl"
fi

$EXECUTABLE $BACKEND resources/shaders/final_blit.hlsl

$EXECUTABLE $BACKEND resources/shaders/fallback.hlsl

$EXECUTABLE $BACKEND resources/shaders/skybox.hlsl

$EXECUTABLE $BACKEND resources/shaders/standard.hlsl
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND resources/shaders/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA

$EXECUTABLE $BACKEND resources/shaders/shadowCaster.hlsl

$EXECUTABLE $BACKEND resources/shaders/outlineBlit.hlsl

$EXECUTABLE $BACKEND resources/shaders/silhouette.hlsl

$EXECUTABLE $BACKEND resources/shaders/billboard.hlsl

$EXECUTABLE $BACKEND resources/shaders/gizmos.hlsl _INSTANCING