read -p "Platform (windows, apple, android): " PLATFORM

OS=$(uname)
if [ "$OS" = "Darwin" ]; then
    EXECUTABLE="../cmake-build-release/shader_compiler/ShaderCompiler.app/Contents/MacOS/ShaderCompiler"
else
    EXECUTABLE="../cmake-build-release/shader_compiler/ShaderCompiler.exe"
fi

if [ "$PLATFORM" = "windows" ]; then
    BACKEND="opengl"
elif [ "$PLATFORM" = "android" ]; then
    BACKEND="gles"
elif [ "$PLATFORM" = "apple" ]; then
    BACKEND="metal"
fi

BASE_PATH="../core_resources/shaders"

$EXECUTABLE $BACKEND $BASE_PATH/final_blit.hlsl

$EXECUTABLE $BACKEND $BASE_PATH/fallback.hlsl

$EXECUTABLE $BACKEND $BASE_PATH/skybox.hlsl

$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $BASE_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA

$EXECUTABLE $BACKEND $BASE_PATH/shadowCaster.hlsl

$EXECUTABLE $BACKEND $BASE_PATH/outlineBlit.hlsl

$EXECUTABLE $BACKEND $BASE_PATH/silhouette.hlsl

$EXECUTABLE $BACKEND $BASE_PATH/billboard.hlsl

$EXECUTABLE $BACKEND $BASE_PATH/gizmos.hlsl _INSTANCING

$EXECUTABLE $BACKEND $BASE_PATH/editor/shadowMapDebug.hlsl

read -p "Finished compiling shaders for ${PLATFORM} ${BACKEND}" _