if [ -z "$1" ]; then
    echo "Platform (windows, apple, android): "; read PLATFORM
else
    PLATFORM=$1
fi

OS=$(uname)
if [ "$OS" = "Darwin" ]; then
    EXECUTABLE="../cmake-build-release/shader_compiler/ShaderCompiler.app/Contents/MacOS/ShaderCompiler"
else
    EXECUTABLE="../cmake-build-release/shader_compiler/ShaderCompiler.exe"
fi

if [ "$PLATFORM" = "windows" ]; then
    BACKEND="opengl"
elif [ "$PLATFORM" = "android" ]; then
    BACKEND="gles"
elif [ "$PLATFORM" = "apple" ]; then
    BACKEND="metal"
fi

INPUT_PATH="../core_resources/shaders"
OUTPUT_PATH="../build_resources/$PLATFORM/core_resources/shaders"

echo "Start compiling shaders for ${PLATFORM} ${BACKEND}"

$EXECUTABLE $BACKEND $OUTPUT_PATH/final_blit $INPUT_PATH/final_blit.hlsl

$EXECUTABLE $BACKEND $OUTPUT_PATH/fallback $INPUT_PATH/fallback.hlsl

$EXECUTABLE $BACKEND $OUTPUT_PATH/skybox $INPUT_PATH/skybox.hlsl

$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _INSTANCING _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _PER_INSTANCE_DATA
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING
$EXECUTABLE $BACKEND $OUTPUT_PATH/standard $INPUT_PATH/standard.hlsl _DATA_MAP _NORMAL_MAP _REFLECTION _RECEIVE_SHADOWS _INSTANCING _PER_INSTANCE_DATA

$EXECUTABLE $BACKEND $OUTPUT_PATH/shadowCaster $INPUT_PATH/shadowCaster.hlsl

$EXECUTABLE $BACKEND $OUTPUT_PATH/outlineBlit $INPUT_PATH/outlineBlit.hlsl

$EXECUTABLE $BACKEND $OUTPUT_PATH/silhouette $INPUT_PATH/silhouette.hlsl

$EXECUTABLE $BACKEND $OUTPUT_PATH/billboard $INPUT_PATH/billboard.hlsl

$EXECUTABLE $BACKEND $OUTPUT_PATH/gizmos $INPUT_PATH/gizmos.hlsl _INSTANCING

$EXECUTABLE $BACKEND $OUTPUT_PATH/editor/shadowMapDebug $INPUT_PATH/editor/shadowMapDebug.hlsl

echo "Finished compiling shaders for ${PLATFORM} ${BACKEND}";
if [ -z "$1" ]; then
    read _
fi