#ifndef RENDER_ENGINE_GRAPHICS_BACKEND_H
#define RENDER_ENGINE_GRAPHICS_BACKEND_H

#if __has_include("GL/glew.h")
#include <GL/glew.h>
#define REQUIRE_GLEW_INIT
#endif
#if __has_include("OpenGL/glu.h")
#include <OpenGL/glu.h>
#endif
#if __has_include("OpenGL/gl3.h")
#include <OpenGL/gl3.h>
#endif
#if __has_include("OpenGL/gl3ext.h")
#include <OpenGL/gl3ext.h>
#endif

#define GRAPHICS_BACKEND_TYPE_ENUM   GLenum
#define GRAPHICS_BACKEND_TYPE_UINT   GLuint

#define GRAPHICS_BACKEND_TEXTURE_BUFFER                 GL_TEXTURE_BUFFER

#define GRAPHICS_BACKEND_UNSIGNED_INT                   GL_UNSIGNED_INT
#define GRAPHICS_BACKEND_INT                            GL_INT
#define GRAPHICS_BACKEND_FLOAT                          GL_FLOAT
#define GRAPHICS_BACKEND_DOUBLE                         GL_DOUBLE

#define GRAPHICS_BACKEND_DRAW_FRAMEBUFFER   GL_DRAW_FRAMEBUFFER
#define GRAPHICS_BACKEND_READ_FRAMEBUFFER   GL_READ_FRAMEBUFFER
#define GRAPHICS_BACKEND_FRAMEBUFFER        GL_FRAMEBUFFER

#define GRAPHICS_BACKEND_NEAREST                    GL_NEAREST
#define GRAPHICS_BACKEND_LINEAR                     GL_LINEAR

#define GRAPHICS_BACKEND_FLOAT_VEC2 GL_FLOAT_VEC2
#define GRAPHICS_BACKEND_FLOAT_VEC3 GL_FLOAT_VEC3
#define GRAPHICS_BACKEND_FLOAT_VEC4 GL_FLOAT_VEC4

#define GRAPHICS_BACKEND_DOUBLE_VEC2 GL_DOUBLE_VEC2
#define GRAPHICS_BACKEND_DOUBLE_VEC3 GL_DOUBLE_VEC3
#define GRAPHICS_BACKEND_DOUBLE_VEC4 GL_DOUBLE_VEC4

#define GRAPHICS_BACKEND_INT_VEC2 GL_INT_VEC2
#define GRAPHICS_BACKEND_INT_VEC3 GL_INT_VEC3
#define GRAPHICS_BACKEND_INT_VEC4 GL_INT_VEC4

#define GRAPHICS_BACKEND_UNSIGNED_INT_VEC2 GL_UNSIGNED_INT_VEC2
#define GRAPHICS_BACKEND_UNSIGNED_INT_VEC3 GL_UNSIGNED_INT_VEC3
#define GRAPHICS_BACKEND_UNSIGNED_INT_VEC4 GL_UNSIGNED_INT_VEC4

#define GRAPHICS_BACKEND_BOOL       GL_BOOL
#define GRAPHICS_BACKEND_BOOL_VEC2  GL_BOOL_VEC2
#define GRAPHICS_BACKEND_BOOL_VEC3  GL_BOOL_VEC3
#define GRAPHICS_BACKEND_BOOL_VEC4  GL_BOOL_VEC4

#define GRAPHICS_BACKEND_FLOAT_MAT2     GL_FLOAT_MAT2
#define GRAPHICS_BACKEND_FLOAT_MAT3     GL_FLOAT_MAT3
#define GRAPHICS_BACKEND_FLOAT_MAT4     GL_FLOAT_MAT4
#define GRAPHICS_BACKEND_FLOAT_MAT2x3   GL_FLOAT_MAT2x3
#define GRAPHICS_BACKEND_FLOAT_MAT2x4   GL_FLOAT_MAT2x4
#define GRAPHICS_BACKEND_FLOAT_MAT3x2   GL_FLOAT_MAT3x2
#define GRAPHICS_BACKEND_FLOAT_MAT3x4   GL_FLOAT_MAT3x4
#define GRAPHICS_BACKEND_FLOAT_MAT4x2   GL_FLOAT_MAT4x2
#define GRAPHICS_BACKEND_FLOAT_MAT4x3   GL_FLOAT_MAT4x3

#define GRAPHICS_BACKEND_DOUBLE_MAT2    GL_DOUBLE_MAT2
#define GRAPHICS_BACKEND_DOUBLE_MAT3    GL_DOUBLE_MAT3
#define GRAPHICS_BACKEND_DOUBLE_MAT4    GL_DOUBLE_MAT4
#define GRAPHICS_BACKEND_DOUBLE_MAT2x3  GL_DOUBLE_MAT2x3
#define GRAPHICS_BACKEND_DOUBLE_MAT2x4  GL_DOUBLE_MAT2x4
#define GRAPHICS_BACKEND_DOUBLE_MAT3x2  GL_DOUBLE_MAT3x2
#define GRAPHICS_BACKEND_DOUBLE_MAT3x4  GL_DOUBLE_MAT3x4
#define GRAPHICS_BACKEND_DOUBLE_MAT4x2  GL_DOUBLE_MAT4x2
#define GRAPHICS_BACKEND_DOUBLE_MAT4x3  GL_DOUBLE_MAT4x3

#define GRAPHICS_BACKEND_SAMPLER_1D                     GL_SAMPLER_1D
#define GRAPHICS_BACKEND_SAMPLER_2D                     GL_SAMPLER_2D
#define GRAPHICS_BACKEND_SAMPLER_3D                     GL_SAMPLER_3D
#define GRAPHICS_BACKEND_SAMPLER_CUBE                   GL_SAMPLER_CUBE
#define GRAPHICS_BACKEND_SAMPLER_1D_SHADOW              GL_SAMPLER_1D_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_2D_SHADOW              GL_SAMPLER_2D_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_1D_ARRAY               GL_SAMPLER_1D_ARRAY
#define GRAPHICS_BACKEND_SAMPLER_2D_ARRAY               GL_SAMPLER_2D_ARRAY
#define GRAPHICS_BACKEND_SAMPLER_1D_ARRAY_SHADOW        GL_SAMPLER_1D_ARRAY_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_2D_ARRAY_SHADOW        GL_SAMPLER_2D_ARRAY_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_2D_MULTISAMPLE         GL_SAMPLER_2D_MULTISAMPLE
#define GRAPHICS_BACKEND_SAMPLER_2D_MULTISAMPLE_ARRAY   GL_SAMPLER_2D_MULTISAMPLE_ARRAY
#define GRAPHICS_BACKEND_SAMPLER_CUBE_SHADOW            GL_SAMPLER_CUBE_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_BUFFER                 GL_SAMPLER_BUFFER
#define GRAPHICS_BACKEND_SAMPLER_2D_RECT                GL_SAMPLER_2D_RECT
#define GRAPHICS_BACKEND_SAMPLER_2D_RECT_SHADOW         GL_SAMPLER_2D_RECT_SHADOW

#define GRAPHICS_BACKEND_INT_SAMPLER_1D                     GL_INT_SAMPLER_1D
#define GRAPHICS_BACKEND_INT_SAMPLER_2D                     GL_INT_SAMPLER_2D
#define GRAPHICS_BACKEND_INT_SAMPLER_3D                     GL_INT_SAMPLER_3D
#define GRAPHICS_BACKEND_INT_SAMPLER_CUBE                   GL_INT_SAMPLER_CUBE
#define GRAPHICS_BACKEND_INT_SAMPLER_1D_ARRAY               GL_INT_SAMPLER_1D_ARRAY
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_ARRAY               GL_INT_SAMPLER_2D_ARRAY
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_MULTISAMPLE         GL_INT_SAMPLER_2D_MULTISAMPLE
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_MULTISAMPLE_ARRAY   GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
#define GRAPHICS_BACKEND_INT_SAMPLER_BUFFER                 GL_INT_SAMPLER_BUFFER
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_RECT                GL_INT_SAMPLER_2D_RECT

#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_1D                    GL_UNSIGNED_INT_SAMPLER_1D
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D                    GL_UNSIGNED_INT_SAMPLER_2D
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_3D                    GL_UNSIGNED_INT_SAMPLER_3D
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_CUBE                  GL_UNSIGNED_INT_SAMPLER_CUBE
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_1D_ARRAY              GL_UNSIGNED_INT_SAMPLER_1D_ARRAY
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_ARRAY              GL_UNSIGNED_INT_SAMPLER_2D_ARRAY
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE        GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY  GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_BUFFER                GL_UNSIGNED_INT_SAMPLER_BUFFER
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_RECT               GL_UNSIGNED_INT_SAMPLER_2D_RECT

#define GRAPHICS_BACKEND_COLOR_BUFFER_BIT   GL_COLOR_BUFFER_BIT
#define GRAPHICS_BACKEND_DEPTH_BUFFER_BIT   GL_DEPTH_BUFFER_BIT
#define GRAPHICS_BACKEND_STENCIL_BUFFER_BIT GL_STENCIL_BUFFER_BIT

#ifdef GL_ARB_program_interface_query

#define GRAPHICS_BACKEND_NAME_LENGTH                            GL_NAME_LENGTH
#define GRAPHICS_BACKEND_TYPE                                   GL_TYPE
#define GRAPHICS_BACKEND_ARRAY_SIZE                             GL_ARRAY_SIZE
#define GRAPHICS_BACKEND_OFFSET                                 GL_OFFSET
#define GRAPHICS_BACKEND_BLOCK_INDEX                            GL_BLOCK_INDEX
#define GRAPHICS_BACKEND_ARRAY_STRIDE                           GL_ARRAY_STRIDE
#define GRAPHICS_BACKEND_MATRIX_STRIDE                          GL_MATRIX_STRIDE
#define GRAPHICS_BACKEND_IS_ROW_MAJOR                           GL_IS_ROW_MAJOR
#define GRAPHICS_BACKEND_ATOMIC_COUNTER_BUFFER_INDEX            GL_ATOMIC_COUNTER_BUFFER_INDEX
#define GRAPHICS_BACKEND_BUFFER_BINDING                         GL_BUFFER_BINDING
#define GRAPHICS_BACKEND_BUFFER_DATA_SIZE                       GL_BUFFER_DATA_SIZE
#define GRAPHICS_BACKEND_NUM_ACTIVE_VARIABLES                   GL_NUM_ACTIVE_VARIABLES
#define GRAPHICS_BACKEND_ACTIVE_VARIABLES                       GL_ACTIVE_VARIABLES
#define GRAPHICS_BACKEND_REFERENCED_BY_VERTEX_SHADER            GL_REFERENCED_BY_VERTEX_SHADER
#define GRAPHICS_BACKEND_REFERENCED_BY_TESS_CONTROL_SHADER      GL_REFERENCED_BY_TESS_CONTROL_SHADER
#define GRAPHICS_BACKEND_REFERENCED_BY_TESS_EVALUATION_SHADER   GL_REFERENCED_BY_TESS_EVALUATION_SHADER
#define GRAPHICS_BACKEND_REFERENCED_BY_GEOMETRY_SHADER          GL_REFERENCED_BY_GEOMETRY_SHADER
#define GRAPHICS_BACKEND_REFERENCED_BY_FRAGMENT_SHADER          GL_REFERENCED_BY_FRAGMENT_SHADER
#define GRAPHICS_BACKEND_REFERENCED_BY_COMPUTE_SHADER           GL_REFERENCED_BY_COMPUTE_SHADER
#define GRAPHICS_BACKEND_TOP_LEVEL_ARRAY_SIZE                   GL_TOP_LEVEL_ARRAY_SIZE
#define GRAPHICS_BACKEND_TOP_LEVEL_ARRAY_STRIDE                 GL_TOP_LEVEL_ARRAY_STRIDE
#define GRAPHICS_BACKEND_LOCATION                               GL_LOCATION
#define GRAPHICS_BACKEND_LOCATION_INDEX                         GL_LOCATION_INDEX
#define GRAPHICS_BACKEND_IS_PER_PATCH                           GL_IS_PER_PATCH
#else

#define GRAPHICS_BACKEND_NAME_LENGTH                            0
#define GRAPHICS_BACKEND_TYPE                                   0
#define GRAPHICS_BACKEND_ARRAY_SIZE                             0
#define GRAPHICS_BACKEND_OFFSET                                 0
#define GRAPHICS_BACKEND_BLOCK_INDEX                            0
#define GRAPHICS_BACKEND_ARRAY_STRIDE                           0
#define GRAPHICS_BACKEND_MATRIX_STRIDE                          0
#define GRAPHICS_BACKEND_IS_ROW_MAJOR                           0
#define GRAPHICS_BACKEND_ATOMIC_COUNTER_BUFFER_INDEX            0
#define GRAPHICS_BACKEND_BUFFER_BINDING                         0
#define GRAPHICS_BACKEND_BUFFER_DATA_SIZE                       0
#define GRAPHICS_BACKEND_NUM_ACTIVE_VARIABLES                   0
#define GRAPHICS_BACKEND_ACTIVE_VARIABLES                       0
#define GRAPHICS_BACKEND_REFERENCED_BY_VERTEX_SHADER            0
#define GRAPHICS_BACKEND_REFERENCED_BY_TESS_CONTROL_SHADER      0
#define GRAPHICS_BACKEND_REFERENCED_BY_TESS_EVALUATION_SHADER   0
#define GRAPHICS_BACKEND_REFERENCED_BY_GEOMETRY_SHADER          0
#define GRAPHICS_BACKEND_REFERENCED_BY_FRAGMENT_SHADER          0
#define GRAPHICS_BACKEND_REFERENCED_BY_COMPUTE_SHADER           0
#define GRAPHICS_BACKEND_TOP_LEVEL_ARRAY_SIZE                   0
#define GRAPHICS_BACKEND_TOP_LEVEL_ARRAY_STRIDE                 0
#define GRAPHICS_BACKEND_LOCATION                               0
#define GRAPHICS_BACKEND_LOCATION_INDEX                         0
#define GRAPHICS_BACKEND_IS_PER_PATCH                           0
#endif

#ifdef GL_ARB_shader_subroutine
#define GRAPHICS_BACKEND_NUM_COMPATIBLE_SUBROUTINES     GL_NUM_COMPATIBLE_SUBROUTINES
#define GRAPHICS_BACKEND_COMPATIBLE_SUBROUTINES         GL_COMPATIBLE_SUBROUTINES
#else
#define GRAPHICS_BACKEND_NUM_COMPATIBLE_SUBROUTINES     0
#define GRAPHICS_BACKEND_COMPATIBLE_SUBROUTINES         0
#endif

#ifdef GL_ARB_enhanced_layouts
#define GRAPHICS_BACKEND_LOCATION_COMPONENT                 GL_LOCATION_COMPONENT
#define GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_BUFFER_INDEX    GL_TRANSFORM_FEEDBACK_BUFFER_INDEX
#define GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_BUFFER_STRIDE   GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE
#else
#define GRAPHICS_BACKEND_LOCATION_COMPONENT                 0
#define GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_BUFFER_INDEX    0
#define GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_BUFFER_STRIDE   0
#endif

#define GRAPHICS_BACKEND_COLOR_BUFFER_BIT       GL_COLOR_BUFFER_BIT
#define GRAPHICS_BACKEND_DEPTH_BUFFER_BIT       GL_DEPTH_BUFFER_BIT
#define GRAPHICS_BACKEND_STENCIL_BUFFER_BIT     GL_STENCIL_BUFFER_BIT

#endif //RENDER_ENGINE_GRAPHICS_BACKEND_H
