#ifndef RENDER_ENGINE_GRAPHICS_BACKEND_H
#define RENDER_ENGINE_GRAPHICS_BACKEND_H

#if __has_include("GL/glew.h")
#include <GL/glew.h>
#define REQUIRE_GLEW_INIT
#endif
#if __has_include("OpenGL/glu.h")
#include <OpenGL/glu.h>
#endif
#if __has_include("OpenGL/gl3.h")
#include <OpenGL/gl3.h>
#endif
#if __has_include("OpenGL/gl3ext.h")
#include <OpenGL/gl3ext.h>
#endif

#define GRAPHICS_BACKEND_TYPE_ENUM   GLenum

#define GRAPHICS_BACKEND_UNSIGNED_INT                   GL_UNSIGNED_INT
#define GRAPHICS_BACKEND_INT                            GL_INT
#define GRAPHICS_BACKEND_FLOAT                          GL_FLOAT
#define GRAPHICS_BACKEND_DOUBLE                         GL_DOUBLE

#define GRAPHICS_BACKEND_FLOAT_VEC2 GL_FLOAT_VEC2
#define GRAPHICS_BACKEND_FLOAT_VEC3 GL_FLOAT_VEC3
#define GRAPHICS_BACKEND_FLOAT_VEC4 GL_FLOAT_VEC4

#define GRAPHICS_BACKEND_DOUBLE_VEC2 GL_DOUBLE_VEC2
#define GRAPHICS_BACKEND_DOUBLE_VEC3 GL_DOUBLE_VEC3
#define GRAPHICS_BACKEND_DOUBLE_VEC4 GL_DOUBLE_VEC4

#define GRAPHICS_BACKEND_INT_VEC2 GL_INT_VEC2
#define GRAPHICS_BACKEND_INT_VEC3 GL_INT_VEC3
#define GRAPHICS_BACKEND_INT_VEC4 GL_INT_VEC4

#define GRAPHICS_BACKEND_UNSIGNED_INT_VEC2 GL_UNSIGNED_INT_VEC2
#define GRAPHICS_BACKEND_UNSIGNED_INT_VEC3 GL_UNSIGNED_INT_VEC3
#define GRAPHICS_BACKEND_UNSIGNED_INT_VEC4 GL_UNSIGNED_INT_VEC4

#define GRAPHICS_BACKEND_BOOL       GL_BOOL
#define GRAPHICS_BACKEND_BOOL_VEC2  GL_BOOL_VEC2
#define GRAPHICS_BACKEND_BOOL_VEC3  GL_BOOL_VEC3
#define GRAPHICS_BACKEND_BOOL_VEC4  GL_BOOL_VEC4

#define GRAPHICS_BACKEND_FLOAT_MAT2     GL_FLOAT_MAT2
#define GRAPHICS_BACKEND_FLOAT_MAT3     GL_FLOAT_MAT3
#define GRAPHICS_BACKEND_FLOAT_MAT4     GL_FLOAT_MAT4
#define GRAPHICS_BACKEND_FLOAT_MAT2x3   GL_FLOAT_MAT2x3
#define GRAPHICS_BACKEND_FLOAT_MAT2x4   GL_FLOAT_MAT2x4
#define GRAPHICS_BACKEND_FLOAT_MAT3x2   GL_FLOAT_MAT3x2
#define GRAPHICS_BACKEND_FLOAT_MAT3x4   GL_FLOAT_MAT3x4
#define GRAPHICS_BACKEND_FLOAT_MAT4x2   GL_FLOAT_MAT4x2
#define GRAPHICS_BACKEND_FLOAT_MAT4x3   GL_FLOAT_MAT4x3

#define GRAPHICS_BACKEND_DOUBLE_MAT2    GL_DOUBLE_MAT2
#define GRAPHICS_BACKEND_DOUBLE_MAT3    GL_DOUBLE_MAT3
#define GRAPHICS_BACKEND_DOUBLE_MAT4    GL_DOUBLE_MAT4
#define GRAPHICS_BACKEND_DOUBLE_MAT2x3  GL_DOUBLE_MAT2x3
#define GRAPHICS_BACKEND_DOUBLE_MAT2x4  GL_DOUBLE_MAT2x4
#define GRAPHICS_BACKEND_DOUBLE_MAT3x2  GL_DOUBLE_MAT3x2
#define GRAPHICS_BACKEND_DOUBLE_MAT3x4  GL_DOUBLE_MAT3x4
#define GRAPHICS_BACKEND_DOUBLE_MAT4x2  GL_DOUBLE_MAT4x2
#define GRAPHICS_BACKEND_DOUBLE_MAT4x3  GL_DOUBLE_MAT4x3

#define GRAPHICS_BACKEND_SAMPLER_1D                     GL_SAMPLER_1D
#define GRAPHICS_BACKEND_SAMPLER_2D                     GL_SAMPLER_2D
#define GRAPHICS_BACKEND_SAMPLER_3D                     GL_SAMPLER_3D
#define GRAPHICS_BACKEND_SAMPLER_CUBE                   GL_SAMPLER_CUBE
#define GRAPHICS_BACKEND_SAMPLER_1D_SHADOW              GL_SAMPLER_1D_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_2D_SHADOW              GL_SAMPLER_2D_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_1D_ARRAY               GL_SAMPLER_1D_ARRAY
#define GRAPHICS_BACKEND_SAMPLER_2D_ARRAY               GL_SAMPLER_2D_ARRAY
#define GRAPHICS_BACKEND_SAMPLER_1D_ARRAY_SHADOW        GL_SAMPLER_1D_ARRAY_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_2D_ARRAY_SHADOW        GL_SAMPLER_2D_ARRAY_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_2D_MULTISAMPLE         GL_SAMPLER_2D_MULTISAMPLE
#define GRAPHICS_BACKEND_SAMPLER_2D_MULTISAMPLE_ARRAY   GL_SAMPLER_2D_MULTISAMPLE_ARRAY
#define GRAPHICS_BACKEND_SAMPLER_CUBE_SHADOW            GL_SAMPLER_CUBE_SHADOW
#define GRAPHICS_BACKEND_SAMPLER_BUFFER                 GL_SAMPLER_BUFFER
#define GRAPHICS_BACKEND_SAMPLER_2D_RECT                GL_SAMPLER_2D_RECT
#define GRAPHICS_BACKEND_SAMPLER_2D_RECT_SHADOW         GL_SAMPLER_2D_RECT_SHADOW

#define GRAPHICS_BACKEND_INT_SAMPLER_1D                     GL_INT_SAMPLER_1D
#define GRAPHICS_BACKEND_INT_SAMPLER_2D                     GL_INT_SAMPLER_2D
#define GRAPHICS_BACKEND_INT_SAMPLER_3D                     GL_INT_SAMPLER_3D
#define GRAPHICS_BACKEND_INT_SAMPLER_CUBE                   GL_INT_SAMPLER_CUBE
#define GRAPHICS_BACKEND_INT_SAMPLER_1D_ARRAY               GL_INT_SAMPLER_1D_ARRAY
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_ARRAY               GL_INT_SAMPLER_2D_ARRAY
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_MULTISAMPLE         GL_INT_SAMPLER_2D_MULTISAMPLE
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_MULTISAMPLE_ARRAY   GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
#define GRAPHICS_BACKEND_INT_SAMPLER_BUFFER                 GL_INT_SAMPLER_BUFFER
#define GRAPHICS_BACKEND_INT_SAMPLER_2D_RECT                GL_INT_SAMPLER_2D_RECT

#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_1D                    GL_UNSIGNED_INT_SAMPLER_1D
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D                    GL_UNSIGNED_INT_SAMPLER_2D
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_3D                    GL_UNSIGNED_INT_SAMPLER_3D
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_CUBE                  GL_UNSIGNED_INT_SAMPLER_CUBE
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_1D_ARRAY              GL_UNSIGNED_INT_SAMPLER_1D_ARRAY
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_ARRAY              GL_UNSIGNED_INT_SAMPLER_2D_ARRAY
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE        GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY  GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_BUFFER                GL_UNSIGNED_INT_SAMPLER_BUFFER
#define GRAPHICS_BACKEND_UNSIGNED_INT_SAMPLER_2D_RECT               GL_UNSIGNED_INT_SAMPLER_2D_RECT

#endif //RENDER_ENGINE_GRAPHICS_BACKEND_H
