#ifndef RENDER_ENGINE_GRAPHICS_BACKEND_MACROS_H
#define RENDER_ENGINE_GRAPHICS_BACKEND_MACROS_H

#if defined(OPENGL_SHADER)

    #define SCREEN_UV_UPSIDE_DOWN 0

#elif defined(METAL_SHADER)

    #define SCREEN_UV_UPSIDE_DOWN 1

#endif

#endif //RENDER_ENGINE_GRAPHICS_BACKEND_MACROS_H
