#ifndef STANDARD_SHADER_SHARED_CODE
#define STANDARD_SHADER_SHARED_CODE

#include "../common/per_draw_data.cg"

#ifdef _PER_INSTANCE_DATA
    BEGIN_PER_INSTANCE_DATA
        vec4 _Color;
        float _Size;
    END_PER_INSTANCE_DATA
#endif

#if defined(VERTEX_PROGRAM)
out
#elif defined(FRAGMENT_PROGRAM)
in
#endif
Varyings
{
    vec3 PositionWS;
    vec3 NormalWS;
#ifdef _NORMAL_MAP
    vec3 TangentWS;
#endif
    vec2 UV;
    DECLARE_INSTANCE_ID_VARYING
} vars;

#endif