#ifndef OPENGL_STUDY_SHADER_LOADER_UTILS_H
#define OPENGL_STUDY_SHADER_LOADER_UTILS_H

namespace ShaderLoaderUtils
{
    constexpr int SUPPORTED_SHADERS_COUNT = 3;
}

#endif //OPENGL_STUDY_SHADER_LOADER_UTILS_H
