#ifndef OPENGL_STUDY_BLEND_FACTOR_H
#define OPENGL_STUDY_BLEND_FACTOR_H

#include "graphics_backend.h"

enum class BlendFactor : GRAPHICS_BACKEND_TYPE_ENUM
{
    ZERO    = GRAPHICS_BACKEND_ZERO,
    ONE     = GRAPHICS_BACKEND_ONE,

    SRC_COLOR               = GRAPHICS_BACKEND_SRC_COLOR,
    ONE_MINUS_SRC_COLOR     = GRAPHICS_BACKEND_ONE_MINUS_SRC_COLOR,
    DST_COLOR               = GRAPHICS_BACKEND_DST_COLOR,
    ONE_MINUS_DST_COLOR     = GRAPHICS_BACKEND_ONE_MINUS_DST_COLOR,

    SRC_ALPHA               = GRAPHICS_BACKEND_SRC_ALPHA,
    ONE_MINUS_SRC_ALPHA     = GRAPHICS_BACKEND_ONE_MINUS_SRC_ALPHA,
    DST_ALPHA               = GRAPHICS_BACKEND_DST_ALPHA,
    ONE_MINUS_DST_ALPHA     = GRAPHICS_BACKEND_ONE_MINUS_DST_ALPHA,

    CONSTANT_COLOR              = GRAPHICS_BACKEND_CONSTANT_COLOR,
    ONE_MINUS_CONSTANT_COLOR    = GRAPHICS_BACKEND_ONE_MINUS_CONSTANT_COLOR,
    CONSTANT_ALPHA              = GRAPHICS_BACKEND_CONSTANT_ALPHA,
    ONE_MINUS_CONSTANT_ALPHA    = GRAPHICS_BACKEND_ONE_MINUS_CONSTANT_ALPHA,

    SRC_ALPHA_SATURATE      = GRAPHICS_BACKEND_SRC_ALPHA_SATURATE,
    SRC1_COLOR              = GRAPHICS_BACKEND_SRC1_COLOR,
    ONE_MINUS_SRC1_COLOR    = GRAPHICS_BACKEND_ONE_MINUS_SRC1_COLOR,
    SRC1_ALPHA              = GRAPHICS_BACKEND_SRC1_ALPHA,
    ONE_MINUS_SRC1_ALPHA    = GRAPHICS_BACKEND_ONE_MINUS_SRC1_ALPHA,
};

#endif //OPENGL_STUDY_BLEND_FACTOR_H
