#ifndef RENDER_ENGINE_BLIT_FRAMEBUFFER_MASK_H
#define RENDER_ENGINE_BLIT_FRAMEBUFFER_MASK_H

#include "graphics_backend.h"

enum class BlitFramebufferMask : GRAPHICS_BACKEND_TYPE_ENUM
{
    COLOR    = GRAPHICS_BACKEND_COLOR_BUFFER_BIT,
    DEPTH    = GRAPHICS_BACKEND_DEPTH_BUFFER_BIT,
    STENCIL  = GRAPHICS_BACKEND_STENCIL_BUFFER_BIT,

    COLOR_DEPTH = COLOR | DEPTH,
    COLOR_STENCIL = COLOR | STENCIL,
    DEPTH_STENCIL = DEPTH | STENCIL,

    ALL = COLOR | DEPTH | STENCIL,
};

#endif //RENDER_ENGINE_BLIT_FRAMEBUFFER_MASK_H
