#ifndef RENDER_ENGINE_BLIT_FRAMEBUFFER_FILTER_H
#define RENDER_ENGINE_BLIT_FRAMEBUFFER_FILTER_H

#include "graphics_backend.h"

enum class BlitFramebufferFilter : GRAPHICS_BACKEND_TYPE_ENUM
{
    NEAREST = GRAPHICS_BACKEND_NEAREST,
    LINEAR = GRAPHICS_BACKEND_LINEAR,
};

#endif //RENDER_ENGINE_BLIT_FRAMEBUFFER_FILTER_H
