#ifndef RENDER_ENGINE_BUFFER_BIND_TARGET_H
#define RENDER_ENGINE_BUFFER_BIND_TARGET_H

#include "graphics_backend.h"

enum class BufferBindTarget : GRAPHICS_BACKEND_TYPE_ENUM
{
    ARRAY_BUFFER                = GRAPHICS_BACKEND_ARRAY_BUFFER,
    COPY_READ_BUFFER            = GRAPHICS_BACKEND_COPY_READ_BUFFER,
    COPY_WRITE_BUFFER           = GRAPHICS_BACKEND_COPY_WRITE_BUFFER,
    DRAW_INDIRECT_BUFFER        = GRAPHICS_BACKEND_DRAW_INDIRECT_BUFFER,
    ELEMENT_ARRAY_BUFFER        = GRAPHICS_BACKEND_ELEMENT_ARRAY_BUFFER,
    PIXEL_PACK_BUFFER           = GRAPHICS_BACKEND_PIXEL_PACK_BUFFER,
    PIXEL_UNPACK_BUFFER         = GRAPHICS_BACKEND_PIXEL_UNPACK_BUFFER,
    TEXTURE_BUFFER              = GRAPHICS_BACKEND_TEXTURE_BUFFER,
    TRANSFORM_FEEDBACK_BUFFER   = GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_BUFFER,
    UNIFORM_BUFFER              = GRAPHICS_BACKEND_UNIFORM_BUFFER,
    DISPATCH_INDIRECT_BUFFER    = GRAPHICS_BACKEND_DISPATCH_INDIRECT_BUFFER,
    QUERY_BUFFER                = GRAPHICS_BACKEND_QUERY_BUFFER,
    SHADER_STORAGE_BUFFER       = GRAPHICS_BACKEND_SHADER_STORAGE_BUFFER,
};

#endif //RENDER_ENGINE_BUFFER_BIND_TARGET_H
