#ifndef RENDER_ENGINE_BUFFER_USAGE_HINT_H
#define RENDER_ENGINE_BUFFER_USAGE_HINT_H

enum class BufferUsageHint
{
    STREAM_DRAW,
    STREAM_READ,
    STREAM_COPY,

    STATIC_DRAW,
    STATIC_READ,
    STATIC_COPY,

    DYNAMIC_DRAW,
    DYNAMIC_READ,
    DYNAMIC_COPY,
};

#endif //RENDER_ENGINE_BUFFER_USAGE_HINT_H
