#ifndef RENDER_ENGINE_BUFFER_TYPE_H
#define RENDER_ENGINE_BUFFER_TYPE_H

enum class BufferType
{
    RAW_BYTE_BUFFER,
    STRUCTURED_BUFFER,
    CONSTANT_BUFFER
};

#endif //RENDER_ENGINE_BUFFER_TYPE_H
