#ifndef RENDER_ENGINE_CULL_FACE_ORIENTATION_H
#define RENDER_ENGINE_CULL_FACE_ORIENTATION_H

enum class CullFaceOrientation
{
    CLOCKWISE,
    COUNTER_CLOCKWISE,
};

#endif //RENDER_ENGINE_CULL_FACE_ORIENTATION_H
