#ifndef RENDER_ENGINE_DEPTH_FUNCTION_H
#define RENDER_ENGINE_DEPTH_FUNCTION_H

enum class DepthFunction
{
    NEVER,
    LESS,
    EQUAL,
    LEQUAL,
    GREATER,
    NOTEQUAL,
    GEQUAL,
    ALWAYS,
};

#endif //RENDER_ENGINE_DEPTH_FUNCTION_H
