#ifndef OPENGL_STUDY_FRAMEBUFFER_ATTACHMENT_H
#define OPENGL_STUDY_FRAMEBUFFER_ATTACHMENT_H

#include "graphics_backend.h"

enum class FramebufferAttachment : GRAPHICS_BACKEND_TYPE_ENUM
{
    COLOR_ATTACHMENT0           = GRAPHICS_BACKEND_COLOR_ATTACHMENT0,
    COLOR_ATTACHMENT1           = GRAPHICS_BACKEND_COLOR_ATTACHMENT1,
    COLOR_ATTACHMENT2           = GRAPHICS_BACKEND_COLOR_ATTACHMENT2,
    COLOR_ATTACHMENT3           = GRAPHICS_BACKEND_COLOR_ATTACHMENT3,
    COLOR_ATTACHMENT4           = GRAPHICS_BACKEND_COLOR_ATTACHMENT4,
    COLOR_ATTACHMENT5           = GRAPHICS_BACKEND_COLOR_ATTACHMENT5,
    COLOR_ATTACHMENT6           = GRAPHICS_BACKEND_COLOR_ATTACHMENT6,
    COLOR_ATTACHMENT7           = GRAPHICS_BACKEND_COLOR_ATTACHMENT7,
    COLOR_ATTACHMENT8           = GRAPHICS_BACKEND_COLOR_ATTACHMENT8,
    COLOR_ATTACHMENT9           = GRAPHICS_BACKEND_COLOR_ATTACHMENT9,
    COLOR_ATTACHMENT10          = GRAPHICS_BACKEND_COLOR_ATTACHMENT10,
    COLOR_ATTACHMENT11          = GRAPHICS_BACKEND_COLOR_ATTACHMENT11,
    COLOR_ATTACHMENT12          = GRAPHICS_BACKEND_COLOR_ATTACHMENT12,
    COLOR_ATTACHMENT13          = GRAPHICS_BACKEND_COLOR_ATTACHMENT13,
    COLOR_ATTACHMENT14          = GRAPHICS_BACKEND_COLOR_ATTACHMENT14,
    COLOR_ATTACHMENT15          = GRAPHICS_BACKEND_COLOR_ATTACHMENT15,
    DEPTH_ATTACHMENT            = GRAPHICS_BACKEND_DEPTH_ATTACHMENT,
    STENCIL_ATTACHMENT          = GRAPHICS_BACKEND_STENCIL_ATTACHMENT,
    DEPTH_STENCIL_ATTACHMENT    = GRAPHICS_BACKEND_DEPTH_STENCIL_ATTACHMENT,
};

#endif //OPENGL_STUDY_FRAMEBUFFER_ATTACHMENT_H
