#ifndef RENDER_ENGINE_FRAMEBUFFER_TARGET_H
#define RENDER_ENGINE_FRAMEBUFFER_TARGET_H

#include "graphics_backend.h"

enum class FramebufferTarget : GRAPHICS_BACKEND_TYPE_ENUM
{
    DRAW_FRAMEBUFFER    = GRAPHICS_BACKEND_DRAW_FRAMEBUFFER,
    READ_FRAMEBUFFER    = GRAPHICS_BACKEND_READ_FRAMEBUFFER,
    FRAMEBUFFER         = GRAPHICS_BACKEND_FRAMEBUFFER,
};

#endif //RENDER_ENGINE_FRAMEBUFFER_TARGET_H
