#ifndef RENDER_ENGINE_FRAMEBUFFER_ATTACHMENT_H
#define RENDER_ENGINE_FRAMEBUFFER_ATTACHMENT_H

enum class FramebufferAttachment
{
    COLOR_ATTACHMENT0 = 0,
    COLOR_ATTACHMENT1 = 1,
    COLOR_ATTACHMENT2 = 2,
    COLOR_ATTACHMENT3 = 3,
    COLOR_ATTACHMENT4 = 4,
    COLOR_ATTACHMENT5 = 5,
    COLOR_ATTACHMENT6 = 6,
    COLOR_ATTACHMENT7 = 7,
    COLOR_ATTACHMENT8 = 8,
    COLOR_ATTACHMENT9 = 9,
    COLOR_ATTACHMENT10 = 10,
    COLOR_ATTACHMENT11 = 11,
    COLOR_ATTACHMENT12 = 12,
    COLOR_ATTACHMENT13 = 13,
    COLOR_ATTACHMENT14 = 14,
    COLOR_ATTACHMENT15 = 15,
    DEPTH_ATTACHMENT = 16,
    STENCIL_ATTACHMENT = 17,
    DEPTH_STENCIL_ATTACHMENT = 18,
};

#endif //RENDER_ENGINE_FRAMEBUFFER_ATTACHMENT_H
