#ifndef RENDER_ENGINE_GRAPHICS_BACKEND_CAPABILITY_H
#define RENDER_ENGINE_GRAPHICS_BACKEND_CAPABILITY_H

#include "graphics_backend.h"

enum class GraphicsBackendCapability : GRAPHICS_BACKEND_TYPE_ENUM
{
    BLEND           = GRAPHICS_BACKEND_BLEND,
    COLOR_LOGIC_OP  = GRAPHICS_BACKEND_COLOR_LOGIC_OP,

    CLIP_DISTANCE0 = GRAPHICS_BACKEND_CLIP_DISTANCE0,
    CLIP_DISTANCE1 = GRAPHICS_BACKEND_CLIP_DISTANCE1,
    CLIP_DISTANCE2 = GRAPHICS_BACKEND_CLIP_DISTANCE2,
    CLIP_DISTANCE3 = GRAPHICS_BACKEND_CLIP_DISTANCE3,
    CLIP_DISTANCE4 = GRAPHICS_BACKEND_CLIP_DISTANCE4,
    CLIP_DISTANCE5 = GRAPHICS_BACKEND_CLIP_DISTANCE5,
    CLIP_DISTANCE6 = GRAPHICS_BACKEND_CLIP_DISTANCE6,
    CLIP_DISTANCE7 = GRAPHICS_BACKEND_CLIP_DISTANCE7,

    CULL_FACE       = GRAPHICS_BACKEND_CULL_FACE,
    DEPTH_CLAMP     = GRAPHICS_BACKEND_DEPTH_CLAMP,
    DEPTH_TEST      = GRAPHICS_BACKEND_DEPTH_TEST,
    SCISSOR_TEST    = GRAPHICS_BACKEND_SCISSOR_TEST,
    STENCIL_TEST    = GRAPHICS_BACKEND_STENCIL_TEST,

    DITHER              = GRAPHICS_BACKEND_DITHER,
    FRAMEBUFFER_SRGB    = GRAPHICS_BACKEND_FRAMEBUFFER_SRGB,
    LINE_SMOOTH         = GRAPHICS_BACKEND_LINE_SMOOTH,
    MULTISAMPLE         = GRAPHICS_BACKEND_MULTISAMPLE,

    POLYGON_OFFSET_FILL     = GRAPHICS_BACKEND_POLYGON_OFFSET_FILL,
    POLYGON_OFFSET_LINE     = GRAPHICS_BACKEND_POLYGON_OFFSET_LINE,
    POLYGON_OFFSET_POINT    = GRAPHICS_BACKEND_POLYGON_OFFSET_POINT,
    POLYGON_SMOOTH          = GRAPHICS_BACKEND_POLYGON_SMOOTH,

    PRIMITIVE_RESTART   = GRAPHICS_BACKEND_PRIMITIVE_RESTART,
    RASTERIZER_DISCARD  = GRAPHICS_BACKEND_RASTERIZER_DISCARD,

    SAMPLE_ALPHA_TO_COVERAGE    = GRAPHICS_BACKEND_SAMPLE_ALPHA_TO_COVERAGE,
    SAMPLE_ALPHA_TO_ONE         = GRAPHICS_BACKEND_SAMPLE_ALPHA_TO_ONE,
    SAMPLE_COVERAGE             = GRAPHICS_BACKEND_SAMPLE_COVERAGE,
    SAMPLE_SHADING              = GRAPHICS_BACKEND_SAMPLE_SHADING,
    SAMPLE_MASK                 = GRAPHICS_BACKEND_SAMPLE_MASK,

    TEXTURE_CUBE_MAP_SEAMLESS   = GRAPHICS_BACKEND_TEXTURE_CUBE_MAP_SEAMLESS,
    PROGRAM_POINT_SIZE          = GRAPHICS_BACKEND_PROGRAM_POINT_SIZE,
};

#endif //RENDER_ENGINE_GRAPHICS_BACKEND_CAPABILITY_H
