#ifndef RENDER_ENGINE_INDICES_DATA_TYPE_H
#define RENDER_ENGINE_INDICES_DATA_TYPE_H

enum class IndicesDataType
{
    UNSIGNED_BYTE,
    UNSIGNED_SHORT,
    UNSIGNED_INT,
};

#endif //RENDER_ENGINE_INDICES_DATA_TYPE_H
