#ifndef RENDER_ENGINE_PRIMITIVE_TYPE_H
#define RENDER_ENGINE_PRIMITIVE_TYPE_H

#include "graphics_backend.h"

enum class PrimitiveType : GRAPHICS_BACKEND_TYPE_ENUM
{
    POINTS                      = GRAPHICS_BACKEND_POINTS,
    LINE_STRIP                  = GRAPHICS_BACKEND_LINE_STRIP,
    LINE_LOOP                   = GRAPHICS_BACKEND_LINE_LOOP,
    LINES                       = GRAPHICS_BACKEND_LINES,
    LINE_STRIP_ADJACENCY        = GRAPHICS_BACKEND_LINE_STRIP_ADJACENCY,
    LINES_ADJACENCY             = GRAPHICS_BACKEND_LINES_ADJACENCY,
    TRIANGLE_STRIP              = GRAPHICS_BACKEND_TRIANGLE_STRIP,
    TRIANGLE_FAN                = GRAPHICS_BACKEND_TRIANGLE_FAN,
    TRIANGLES                   = GRAPHICS_BACKEND_TRIANGLES,
    TRIANGLE_STRIP_ADJACENCY    = GRAPHICS_BACKEND_TRIANGLE_STRIP_ADJACENCY,
    TRIANGLES_ADJACENCY         = GRAPHICS_BACKEND_TRIANGLES_ADJACENCY,
    PATCHES                     = GRAPHICS_BACKEND_PATCHES,
};

#endif //RENDER_ENGINE_PRIMITIVE_TYPE_H
