#ifndef RENDER_ENGINE_PRIMITIVE_TYPE_H
#define RENDER_ENGINE_PRIMITIVE_TYPE_H

enum class PrimitiveType
{
    POINTS,
    LINE_STRIP,
    LINE_LOOP,
    LINES,
    LINE_STRIP_ADJACENCY,
    LINES_ADJACENCY,
    TRIANGLE_STRIP,
    TRIANGLE_FAN,
    TRIANGLES,
    TRIANGLE_STRIP_ADJACENCY,
    TRIANGLES_ADJACENCY,
    PATCHES,
};

#endif //RENDER_ENGINE_PRIMITIVE_TYPE_H
