#ifndef OPENGL_STUDY_PROGRAM_INTERFACE_H
#define OPENGL_STUDY_PROGRAM_INTERFACE_H

#include "graphics_backend.h"

enum class ProgramInterface : GRAPHICS_BACKEND_TYPE_ENUM
{
    UNIFORM                 = GRAPHICS_BACKEND_UNIFORM,
    UNIFORM_BLOCK           = GRAPHICS_BACKEND_UNIFORM_BLOCK,
    SHADER_STORAGE_BLOCK    = GRAPHICS_BACKEND_SHADER_STORAGE_BLOCK,

    ATOMIC_COUNTER_BUFFER       = GRAPHICS_BACKEND_ATOMIC_COUNTER_BUFFER,
    TRANSFORM_FEEDBACK_BUFFER   = GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_BUFFER,

    PROGRAM_INPUT   = GRAPHICS_BACKEND_PROGRAM_INPUT,
    PROGRAM_OUTPUT  = GRAPHICS_BACKEND_PROGRAM_OUTPUT,

    VERTEX_SUBROUTINE           = GRAPHICS_BACKEND_VERTEX_SUBROUTINE,
    TESS_CONTROL_SUBROUTINE     = GRAPHICS_BACKEND_TESS_CONTROL_SUBROUTINE,
    TESS_EVALUATION_SUBROUTINE  = GRAPHICS_BACKEND_TESS_EVALUATION_SUBROUTINE,
    GEOMETRY_SUBROUTINE         = GRAPHICS_BACKEND_GEOMETRY_SUBROUTINE,
    FRAGMENT_SUBROUTINE         = GRAPHICS_BACKEND_FRAGMENT_SUBROUTINE,
    COMPUTE_SUBROUTINE          = GRAPHICS_BACKEND_COMPUTE_SUBROUTINE,

    VERTEX_SUBROUTINE_UNIFORM           = GRAPHICS_BACKEND_VERTEX_SUBROUTINE_UNIFORM,
    TESS_CONTROL_SUBROUTINE_UNIFORM     = GRAPHICS_BACKEND_TESS_CONTROL_SUBROUTINE_UNIFORM,
    TESS_EVALUATION_SUBROUTINE_UNIFORM  = GRAPHICS_BACKEND_TESS_EVALUATION_SUBROUTINE_UNIFORM,
    GEOMETRY_SUBROUTINE_UNIFORM         = GRAPHICS_BACKEND_GEOMETRY_SUBROUTINE_UNIFORM,
    FRAGMENT_SUBROUTINE_UNIFORM         = GRAPHICS_BACKEND_FRAGMENT_SUBROUTINE_UNIFORM,
    COMPUTE_SUBROUTINE_UNIFORM          = GRAPHICS_BACKEND_COMPUTE_SUBROUTINE_UNIFORM,

    TRANSFORM_FEEDBACK_VARYING = GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_VARYING,

    BUFFER_VARIABLE = GRAPHICS_BACKEND_BUFFER_VARIABLE,
};

#endif //OPENGL_STUDY_PROGRAM_INTERFACE_H
