#ifndef OPENGL_STUDY_PROGRAM_PARAMETER_H
#define OPENGL_STUDY_PROGRAM_PARAMETER_H

#include "graphics_backend.h"

enum class ProgramParameter : GRAPHICS_BACKEND_TYPE_ENUM
{
    DELETE_STATUS       = GRAPHICS_BACKEND_DELETE_STATUS,
    LINK_STATUS         = GRAPHICS_BACKEND_LINK_STATUS,
    VALIDATE_STATUS     = GRAPHICS_BACKEND_VALIDATE_STATUS,
    INFO_LOG_LENGTH     = GRAPHICS_BACKEND_INFO_LOG_LENGTH,

    ATTACHED_SHADERS = GRAPHICS_BACKEND_ATTACHED_SHADERS,

    ACTIVE_ATTRIBUTES               = GRAPHICS_BACKEND_ACTIVE_ATTRIBUTES,
    ACTIVE_ATTRIBUTE_MAX_LENGTH     = GRAPHICS_BACKEND_ACTIVE_ATTRIBUTE_MAX_LENGTH,

    ACTIVE_UNIFORMS                         = GRAPHICS_BACKEND_ACTIVE_UNIFORMS,
    ACTIVE_UNIFORM_BLOCKS                   = GRAPHICS_BACKEND_ACTIVE_UNIFORM_BLOCKS,
    ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH    = GRAPHICS_BACKEND_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH,
    ACTIVE_UNIFORM_MAX_LENGTH               = GRAPHICS_BACKEND_ACTIVE_UNIFORM_MAX_LENGTH,

    PROGRAM_BINARY_LENGTH = GRAPHICS_BACKEND_PROGRAM_BINARY_LENGTH,

    TRANSFORM_FEEDBACK_BUFFER_MODE          = GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_BUFFER_MODE,
    TRANSFORM_FEEDBACK_VARYINGS             = GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_VARYINGS,
    TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH   = GRAPHICS_BACKEND_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH,

    GEOMETRY_VERTICES_OUT   = GRAPHICS_BACKEND_GEOMETRY_VERTICES_OUT,
    GEOMETRY_INPUT_TYPE     = GRAPHICS_BACKEND_GEOMETRY_INPUT_TYPE,
    GEOMETRY_OUTPUT_TYPE    = GRAPHICS_BACKEND_GEOMETRY_OUTPUT_TYPE,
};

#endif //OPENGL_STUDY_PROGRAM_PARAMETER_H
