#ifndef OPENGL_STUDY_SAMPLER_PARAMETER_H
#define OPENGL_STUDY_SAMPLER_PARAMETER_H

#include "graphics_backend.h"

enum class SamplerParameter : GRAPHICS_BACKEND_TYPE_ENUM
{
    WRAP_S = GRAPHICS_BACKEND_TEXTURE_WRAP_S,
    WRAP_T = GRAPHICS_BACKEND_TEXTURE_WRAP_T,
    WRAP_R = GRAPHICS_BACKEND_TEXTURE_WRAP_R,

    MIN_FILTER = GRAPHICS_BACKEND_TEXTURE_MIN_FILTER,
    MAG_FILTER = GRAPHICS_BACKEND_TEXTURE_MAG_FILTER,

    BORDER_COLOR = GRAPHICS_BACKEND_TEXTURE_BORDER_COLOR,

    MIN_LOD     = GRAPHICS_BACKEND_TEXTURE_MIN_LOD,
    MAX_LOD     = GRAPHICS_BACKEND_TEXTURE_MAX_LOD,
    LOD_BIAS    = GRAPHICS_BACKEND_TEXTURE_LOD_BIAS,

    COMPARE_MODE = GRAPHICS_BACKEND_TEXTURE_COMPARE_MODE,
    COMPARE_FUNC = GRAPHICS_BACKEND_TEXTURE_COMPARE_FUNC,
};

#endif //OPENGL_STUDY_SAMPLER_PARAMETER_H
