#ifndef OPENGL_STUDY_SHADER_PARAMETER_H
#define OPENGL_STUDY_SHADER_PARAMETER_H

#include "graphics_backend.h"

enum class ShaderParameter : GRAPHICS_BACKEND_TYPE_ENUM
{
    SHADER_TYPE             = GRAPHICS_BACKEND_SHADER_TYPE,
    DELETE_STATUS           = GRAPHICS_BACKEND_DELETE_STATUS,
    COMPILE_STATUS          = GRAPHICS_BACKEND_COMPILE_STATUS,
    INFO_LOG_LENGTH         = GRAPHICS_BACKEND_INFO_LOG_LENGTH,
    SHADER_SOURCE_LENGTH    = GRAPHICS_BACKEND_SHADER_SOURCE_LENGTH,
};

#endif //OPENGL_STUDY_SHADER_PARAMETER_H
