#ifndef RENDER_ENGINE_SHADER_TYPE_H
#define RENDER_ENGINE_SHADER_TYPE_H

enum class ShaderType
{
    VERTEX_SHADER,
    TESS_CONTROL_SHADER,
    TESS_EVALUATION_SHADER,
    GEOMETRY_SHADER,
    FRAGMENT_SHADER,
};

#endif //RENDER_ENGINE_SHADER_TYPE_H
