#ifndef RENDER_ENGINE_SHADER_TYPE_H
#define RENDER_ENGINE_SHADER_TYPE_H

enum class ShaderType
{
    VERTEX_SHADER,
    FRAGMENT_SHADER,
    COMPUTE_SHADER,

    COUNT
};

#endif //RENDER_ENGINE_SHADER_TYPE_H
