#ifndef RENDER_ENGINE_SHADER_TYPE_H
#define RENDER_ENGINE_SHADER_TYPE_H

#include "graphics_backend.h"

enum class ShaderType : GRAPHICS_BACKEND_TYPE_ENUM
{
    VERTEX_SHADER           = GRAPHICS_BACKEND_VERTEX_SHADER,
    TESS_CONTROL_SHADER     = GRAPHICS_BACKEND_TESS_CONTROL_SHADER,
    TESS_EVALUATION_SHADER  = GRAPHICS_BACKEND_TESS_EVALUATION_SHADER,
    GEOMETRY_SHADER         = GRAPHICS_BACKEND_GEOMETRY_SHADER,
    FRAGMENT_SHADER         = GRAPHICS_BACKEND_FRAGMENT_SHADER,
};

#endif //RENDER_ENGINE_SHADER_TYPE_H
