#ifndef RENDER_ENGINE_STENCIL_OPERATION_H
#define RENDER_ENGINE_STENCIL_OPERATION_H

enum class StencilOperation
{
    KEEP,
    ZERO,
    REPLACE,
    INCREMENT_SATURATE,
    DECREMENT_SATURATE,
    INVERT,
    INCREMENT,
    DECREMENT
};

#endif //RENDER_ENGINE_STENCIL_OPERATION_H
