#ifndef RENDER_ENGINE_STORE_ACTION_H
#define RENDER_ENGINE_STORE_ACTION_H

enum class StoreAction
{
    STORE,
    DONT_CARE,
    MULTISAMPLE_RESOLVE,
    STORE_AND_MULTISAMPLE_RESOLVE,
    UNKNOWN,
    CUSTOM_SAMPLE_DEPTH_STORE
};

#endif //RENDER_ENGINE_STORE_ACTION_H
