#ifndef RENDER_ENGINE_TEXTURE_LEVEL_PARAMETER_H
#define RENDER_ENGINE_TEXTURE_LEVEL_PARAMETER_H

#include "graphics_backend.h"

enum class TextureLevelParameter : GRAPHICS_BACKEND_TYPE_ENUM
{
    WIDTH   = GRAPHICS_BACKEND_TEXTURE_WIDTH,
    HEIGHT  = GRAPHICS_BACKEND_TEXTURE_HEIGHT,
    DEPTH   = GRAPHICS_BACKEND_TEXTURE_DEPTH,

    INTERNAL_FORMAT = GRAPHICS_BACKEND_TEXTURE_INTERNAL_FORMAT,

    RED_SIZE    = GRAPHICS_BACKEND_TEXTURE_RED_SIZE,
    GREEN_SIZE  = GRAPHICS_BACKEND_TEXTURE_GREEN_SIZE,
    BLUE_SIZE   = GRAPHICS_BACKEND_TEXTURE_BLUE_SIZE,
    ALPHA_SIZE  = GRAPHICS_BACKEND_TEXTURE_ALPHA_SIZE,
    DEPTH_SIZE  = GRAPHICS_BACKEND_TEXTURE_DEPTH_SIZE,

    COMPRESSED              = GRAPHICS_BACKEND_TEXTURE_COMPRESSED,
    COMPRESSED_IMAGE_SIZE   = GRAPHICS_BACKEND_TEXTURE_COMPRESSED_IMAGE_SIZE,
};

#endif //RENDER_ENGINE_TEXTURE_LEVEL_PARAMETER_H
