#ifndef RENDER_ENGINE_UNIFORM_DATA_TYPE_H
#define RENDER_ENGINE_UNIFORM_DATA_TYPE_H

enum class TextureDataType
{
    SAMPLER_1D,
    SAMPLER_2D,
    SAMPLER_3D,
    SAMPLER_CUBE,
    SAMPLER_1D_SHADOW,
    SAMPLER_2D_SHADOW,
    SAMPLER_1D_ARRAY,
    SAMPLER_2D_ARRAY,
    SAMPLER_1D_ARRAY_SHADOW,
    SAMPLER_2D_ARRAY_SHADOW,
    SAMPLER_2D_MULTISAMPLE,
    SAMPLER_2D_MULTISAMPLE_ARRAY,
    SAMPLER_CUBE_SHADOW,
    SAMPLER_BUFFER,
    SAMPLER_2D_RECT,
    SAMPLER_2D_RECT_SHADOW,

    INT_SAMPLER_1D,
    INT_SAMPLER_2D,
    INT_SAMPLER_3D,
    INT_SAMPLER_CUBE,
    INT_SAMPLER_1D_ARRAY,
    INT_SAMPLER_2D_ARRAY,
    INT_SAMPLER_2D_MULTISAMPLE,
    INT_SAMPLER_2D_MULTISAMPLE_ARRAY,
    INT_SAMPLER_BUFFER,
    INT_SAMPLER_2D_RECT,

    UNSIGNED_INT_SAMPLER_1D,
    UNSIGNED_INT_SAMPLER_2D,
    UNSIGNED_INT_SAMPLER_3D,
    UNSIGNED_INT_SAMPLER_CUBE,
    UNSIGNED_INT_SAMPLER_1D_ARRAY,
    UNSIGNED_INT_SAMPLER_2D_ARRAY,
    UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE,
    UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY,
    UNSIGNED_INT_SAMPLER_BUFFER,
    UNSIGNED_INT_SAMPLER_2D_RECT,
};

#endif //RENDER_ENGINE_UNIFORM_DATA_TYPE_H
