#ifndef RENDER_ENGINE_TEXTURE_INTERNAL_FORMAT_H
#define RENDER_ENGINE_TEXTURE_INTERNAL_FORMAT_H

#include "graphics_backend.h"

enum class TextureInternalFormat : GRAPHICS_BACKEND_TYPE_ENUM
{
    RED         = GRAPHICS_BACKEND_RED,
    RG          = GRAPHICS_BACKEND_RG,
    RGB         = GRAPHICS_BACKEND_RGB,
    RGBA        = GRAPHICS_BACKEND_RGBA,
    SRGB        = GRAPHICS_BACKEND_SRGB,
    SRGB_ALPHA  = GRAPHICS_BACKEND_SRGB_ALPHA,

    COMPRESSED_RGB          = GRAPHICS_BACKEND_COMPRESSED_RGB,
    COMPRESSED_RGBA         = GRAPHICS_BACKEND_COMPRESSED_RGBA,
    COMPRESSED_SRGB         = GRAPHICS_BACKEND_COMPRESSED_SRGB,
    COMPRESSED_SRGB_ALPHA   = GRAPHICS_BACKEND_COMPRESSED_SRGB_ALPHA,
    COMPRESSED_RED          = GRAPHICS_BACKEND_COMPRESSED_RED,
    COMPRESSED_RG           = GRAPHICS_BACKEND_COMPRESSED_RG,

    R3_G3_B2    = GRAPHICS_BACKEND_R3_G3_B2,
    RGB4        = GRAPHICS_BACKEND_RGB4,
    RGB5        = GRAPHICS_BACKEND_RGB5,
    RGB8        = GRAPHICS_BACKEND_RGB8,
    RGB10       = GRAPHICS_BACKEND_RGB10,
    RGB12       = GRAPHICS_BACKEND_RGB12,
    RGB16       = GRAPHICS_BACKEND_RGB16,
    RGBA2       = GRAPHICS_BACKEND_RGBA2,
    RGBA4       = GRAPHICS_BACKEND_RGBA4,
    RGB5_A1     = GRAPHICS_BACKEND_RGB5_A1,
    RGBA8       = GRAPHICS_BACKEND_RGBA8,
    RGB10_A2    = GRAPHICS_BACKEND_RGB10_A2,
    RGBA12      = GRAPHICS_BACKEND_RGBA12,
    RGBA16      = GRAPHICS_BACKEND_RGBA16,

    COMPRESSED_RGB_S3TC_DXT1_EXT  = GRAPHICS_BACKEND_COMPRESSED_RGB_S3TC_DXT1_EXT,
    COMPRESSED_RGBA_S3TC_DXT1_EXT = GRAPHICS_BACKEND_COMPRESSED_RGBA_S3TC_DXT1_EXT,
    COMPRESSED_RGBA_S3TC_DXT3_EXT = GRAPHICS_BACKEND_COMPRESSED_RGBA_S3TC_DXT3_EXT,
    COMPRESSED_RGBA_S3TC_DXT5_EXT = GRAPHICS_BACKEND_COMPRESSED_RGBA_S3TC_DXT5_EXT,

    COMPRESSED_SRGB_S3TC_DXT1_EXT       = GRAPHICS_BACKEND_COMPRESSED_SRGB_S3TC_DXT1_EXT,
    COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT = GRAPHICS_BACKEND_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT,
    COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT = GRAPHICS_BACKEND_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT,
    COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT = GRAPHICS_BACKEND_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT,

    COMPRESSED_RED_RGTC1            = GRAPHICS_BACKEND_COMPRESSED_RED_RGTC1,
    COMPRESSED_SIGNED_RED_RGTC1     = GRAPHICS_BACKEND_COMPRESSED_SIGNED_RED_RGTC1,
    COMPRESSED_RG_RGTC2             = GRAPHICS_BACKEND_COMPRESSED_RG_RGTC2,
    COMPRESSED_SIGNED_RG_RGTC2      = GRAPHICS_BACKEND_COMPRESSED_SIGNED_RG_RGTC2,

    DEPTH_COMPONENT = GRAPHICS_BACKEND_DEPTH_COMPONENT,
    DEPTH_STENCIL   = GRAPHICS_BACKEND_DEPTH_STENCIL,
};

#endif //RENDER_ENGINE_TEXTURE_INTERNAL_FORMAT_H
