#ifndef RENDER_ENGINE_TEXTURE_TYPE_H
#define RENDER_ENGINE_TEXTURE_TYPE_H

enum class TextureType
{
    TEXTURE_1D,
    TEXTURE_1D_ARRAY,

    TEXTURE_2D,
    TEXTURE_2D_MULTISAMPLE,
    TEXTURE_2D_ARRAY,
    TEXTURE_2D_MULTISAMPLE_ARRAY,

    TEXTURE_3D,

    TEXTURE_CUBEMAP,
    TEXTURE_CUBEMAP_ARRAY,

    TEXTURE_RECTANGLE,
    TEXTURE_BUFFER,
};

#endif //RENDER_ENGINE_TEXTURE_TYPE_H
