#ifndef RENDER_ENGINE_TEXTURE_WRAP_MODE_H
#define RENDER_ENGINE_TEXTURE_WRAP_MODE_H

enum class TextureWrapMode
{
    CLAMP_TO_EDGE,
    CLAMP_TO_BORDER,
    MIRRORED_REPEAT,
    REPEAT,
};

#endif //RENDER_ENGINE_TEXTURE_WRAP_MODE_H
