#ifndef RENDER_ENGINE_TEXTURE_WRAP_MODE_H
#define RENDER_ENGINE_TEXTURE_WRAP_MODE_H

#include "graphics_backend.h"

enum class TextureWrapMode : GRAPHICS_BACKEND_TYPE_ENUM
{
    CLAMP_TO_EDGE       = GRAPHICS_BACKEND_CLAMP_TO_EDGE,
    CLAMP_TO_BORDER     = GRAPHICS_BACKEND_CLAMP_TO_BORDER,
    MIRRORED_REPEAT     = GRAPHICS_BACKEND_MIRRORED_REPEAT,
    REPEAT              = GRAPHICS_BACKEND_REPEAT,
};

#endif //RENDER_ENGINE_TEXTURE_WRAP_MODE_H
