#ifndef RENDER_ENGINE_TEXTURE_FILTERING_MODE_H
#define RENDER_ENGINE_TEXTURE_FILTERING_MODE_H

#include "graphics_backend.h"

enum class TextureFilteringMode : GRAPHICS_BACKEND_TYPE_ENUM
{
    NEAREST                 = GRAPHICS_BACKEND_NEAREST,
    LINEAR                  = GRAPHICS_BACKEND_LINEAR,
    NEAREST_MIPMAP_NEAREST  = GRAPHICS_BACKEND_NEAREST_MIPMAP_NEAREST,
    LINEAR_MIPMAP_NEAREST   = GRAPHICS_BACKEND_LINEAR_MIPMAP_NEAREST,
    NEAREST_MIPMAP_LINEAR   = GRAPHICS_BACKEND_NEAREST_MIPMAP_LINEAR,
    LINEAR_MIPMAP_LINEAR    = GRAPHICS_BACKEND_LINEAR_MIPMAP_LINEAR,
};

#endif //RENDER_ENGINE_TEXTURE_FILTERING_MODE_H
