#ifndef RENDER_ENGINE_UNIFORM_PARAMETER_H
#define RENDER_ENGINE_UNIFORM_PARAMETER_H

#include "graphics_backend.h"

enum class UniformParameter : GRAPHICS_BACKEND_TYPE_ENUM
{
    TYPE            = GRAPHICS_BACKEND_UNIFORM_TYPE,
    SIZE            = GRAPHICS_BACKEND_UNIFORM_SIZE,
    NAME_LENGTH     = GRAPHICS_BACKEND_UNIFORM_NAME_LENGTH,
    BLOCK_INDEX     = GRAPHICS_BACKEND_UNIFORM_BLOCK_INDEX,
    OFFSET          = GRAPHICS_BACKEND_UNIFORM_OFFSET,
    ARRAY_STRIDE    = GRAPHICS_BACKEND_UNIFORM_ARRAY_STRIDE,
    MATRIX_STRIDE   = GRAPHICS_BACKEND_UNIFORM_MATRIX_STRIDE,
    IS_ROW_MAJOR    = GRAPHICS_BACKEND_UNIFORM_IS_ROW_MAJOR,
};

#endif //RENDER_ENGINE_UNIFORM_PARAMETER_H
