#ifndef RENDER_ENGINE_VERTEX_ATTRIBUTE_SEMANTIC_H
#define RENDER_ENGINE_VERTEX_ATTRIBUTE_SEMANTIC_H

enum class VertexAttributeSemantic
{
    POSITION,
    TEXCOORD,
    NORMAL,
    TANGENT
};

#endif //RENDER_ENGINE_VERTEX_ATTRIBUTE_SEMANTIC_H
