#ifndef RENDER_ENGINE_VERTEX_ATTRIBUTE_DATA_TYPE_H
#define RENDER_ENGINE_VERTEX_ATTRIBUTE_DATA_TYPE_H

enum class VertexAttributeDataType
{
    BYTE,
    UNSIGNED_BYTE,
    SHORT,
    UNSIGNED_SHORT,
    INT,
    UNSIGNED_INT,
    HALF_FLOAT,
    FLOAT,
    DOUBLE,
    FIXED,
    INT_2_10_10_10_REV,
    UNSIGNED_INT_2_10_10_10_REV,
    UNSIGNED_INT_10F_11F_11F_REV,
};

#endif //RENDER_ENGINE_VERTEX_ATTRIBUTE_DATA_TYPE_H
